/**
 * This import is automatically generated by Meteor-Vite while building for production.
 * It should only point to your Vite production bundle, and is perfectly safe to remove or commit.
 *
 * If you're seeing this import including any other files like the Vite plugin itself,
 * Meteor might be trying to import ESM over CommonJS. Please open an issue if this happens.
 * Shouldn't be dangerous, but it might bloat your client bundle.
**/
import "./../_vite-bundle/client/meteor-entry.js._vite-bundle.tmp";



import { Meteor } from 'meteor/meteor';
import { mount } from 'svelte';
import App from '../imports/ui/App.svelte';


Meteor.startup(() => {
  mount(App, { target: document.getElementById("app") });
});